// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygbxmdygswdjleecztmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnYnhtZHlnc3dkamxlZWN6dG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzc4NzMsImV4cCI6MjA3MjcxMzg3M30.vAYBDR3edeQxOPWrfuSVlbTxakga9_yOdPRGdsYun0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});